version: "3.9"

services:
  mern-app:
    image: node:20 
    container_name: mern-app-partII
    working_dir: /app
    volumes:
      - .:/app              
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules  
    ports:
      - "8000:7000"       
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - DEPLOY_ENV=ec2
      - PORT=7000
    command: bash -c "cd frontend && npm install && npm run build && mkdir -p ../backend/public && cp -r dist/* ../backend/public/ && cd ../backend && npm install && npm run build && node dist/server.js"